# Override the default port (8080) of the web server:
server:
    port: 8081
    servlet:
        context-path: /account

# Configure the prot and URI of the back-end REST-API
data:
    port: 8080
    url: http://localhost:8080/api