# Override the default port (8080) of the web server:
server:
    port: 8081
    servlet:
        context-path: /account

# Configure the prot and URI of the back-end REST-API
data:
    service:
        port: 8080
        url: ${DB_URL:http://localhost}:${DB_PORT:8080}/api

jwt:
    secret: "shaimasSuperSecureJWTSecretKey123456"

app:
 internal: 
  secret: "dev-internal-secret"